[chardev "ipmi-relay"]
backend = "socket"
path = "/run/qemu-ipmi-relay/ipmi.sock"
reconnect-ms = "1000"

[device "host-bmc"]
driver = "ipmi-bmc-extern"
chardev = "ipmi-relay"

[device "host-kcs"]
driver = "isa-ipmi-kcs"
bmc = "host-bmc"
